use_frameworks!

target 'CustomPodTest_Example' do
  pod 'CustomPodTest', :path => '../'

  target 'CustomPodTest_Tests' do
    pod 'CustomPodTest', :path => '../'
    
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
